"""
curriculum.py — Smart Curriculum Engine
Recognises 34 subjects across 10 categories with 80+ keyword aliases.
Generates structured study plans with specific topics in learning order.
Unrecognised subjects get a generic review/practice/assessment plan.
Implements FR-12.
"""

CURRICULUM_DB = {

    "python": {
        "name": "Python Programming",
        "topics": [
            "Variables, Data Types and Operators",
            "Strings and String Methods",
            "Control Flow: if/elif/else",
            "Loops: for and while",
            "Functions and Parameters",
            "Lists, Tuples and Sets",
            "Dictionaries and Data Structures",
            "File Handling and I/O",
            "Error Handling and Exceptions",
            "Object-Oriented Programming: Classes",
            "OOP: Inheritance and Polymorphism",
            "Modules and Packages",
            "List Comprehensions and Generators",
            "Working with APIs and JSON",
            "Unit Testing with pytest",
            "Lambda Functions and Map/Filter",
            "Regular Expressions",
            "Database Access with SQLite",
            "Virtual Environments and pip",
            "Mini Project: Build a CLI Tool",
            "Practice Problems and Debugging",
            "Review and Self-Assessment",
        ]
    },
    "java": {
        "name": "Java Programming",
        "topics": [
            "JDK Setup and Hello World",
            "Variables, Types and Operators",
            "Control Flow: if/else and switch",
            "Loops: for, while, do-while",
            "Methods and Parameters",
            "Arrays and ArrayLists",
            "Object-Oriented Programming: Classes",
            "OOP: Inheritance and Interfaces",
            "OOP: Polymorphism and Abstraction",
            "Exception Handling: try/catch",
            "Collections Framework: List, Set, Map",
            "Generics and Type Safety",
            "File I/O and Streams",
            "String Manipulation and StringBuilder",
            "Lambda Expressions and Functional Interfaces",
            "Multithreading Basics",
            "JDBC and Database Connectivity",
            "Design Patterns: Singleton, Factory",
            "JUnit Testing",
            "Mini Project: Console Application",
            "Practice Problems and Review",
        ]
    },
    "javascript": {
        "name": "JavaScript",
        "topics": [
            "Variables: var, let, const",
            "Data Types and Type Coercion",
            "Functions and Arrow Functions",
            "Control Flow and Loops",
            "Arrays and Array Methods",
            "Objects and Destructuring",
            "DOM Manipulation",
            "Event Handling and Listeners",
            "Asynchronous JS: Callbacks",
            "Promises and async/await",
            "Fetch API and HTTP Requests",
            "ES6+ Features: Spread, Rest, Template Literals",
            "Classes and Prototypes",
            "Error Handling with try/catch",
            "Local Storage and Session Storage",
            "Modules: import/export",
            "JSON Parsing and APIs",
            "Closures and Scope",
            "Higher-Order Functions",
            "Mini Project: Interactive Web App",
            "Practice and Debugging",
        ]
    },
    "c++": {
        "name": "C++ Programming",
        "topics": [
            "Compilation, Setup and Hello World",
            "Variables, Data Types and I/O",
            "Operators and Expressions",
            "Control Structures: if/else, switch",
            "Loops: for, while, do-while",
            "Functions and Overloading",
            "Arrays and Strings",
            "Pointers and References",
            "Dynamic Memory: new and delete",
            "Classes and Objects",
            "Constructors and Destructors",
            "Inheritance and Polymorphism",
            "Operator Overloading",
            "Templates and Generic Programming",
            "Standard Template Library (STL)",
            "File I/O with fstream",
            "Exception Handling",
            "Smart Pointers and RAII",
            "Practice Problems and Review",
        ]
    },
    "c#": {
        "name": "C# Programming",
        "topics": [
            "Setup .NET and Hello World",
            "Variables, Types and Operators",
            "Control Flow and Loops",
            "Methods and Parameters",
            "Arrays and Collections",
            "OOP: Classes and Objects",
            "OOP: Inheritance and Interfaces",
            "Properties and Encapsulation",
            "Exception Handling",
            "LINQ Basics",
            "Delegates and Events",
            "Generics",
            "File I/O",
            "Async/Await Programming",
            "Entity Framework Basics",
            "Unit Testing with NUnit",
            "Mini Project: Console App",
            "Practice and Review",
        ]
    },
    "html css": {
        "name": "HTML and CSS",
        "topics": [
            "HTML Document Structure and Tags",
            "Text Elements: Headings, Paragraphs, Lists",
            "Links, Images and Media",
            "Forms and Input Elements",
            "Semantic HTML5 Elements",
            "CSS Selectors and Properties",
            "Box Model: Margin, Padding, Border",
            "Colours, Backgrounds and Gradients",
            "Typography and Google Fonts",
            "Flexbox Layout",
            "CSS Grid Layout",
            "Responsive Design and Media Queries",
            "CSS Variables and Custom Properties",
            "Transitions and Animations",
            "Positioning: Static, Relative, Absolute, Fixed",
            "Build a Landing Page Project",
            "Practice and Review",
        ]
    },
    "react": {
        "name": "React Development",
        "topics": [
            "JSX and Component Basics",
            "Props and Component Communication",
            "State with useState",
            "Event Handling in React",
            "Conditional Rendering",
            "Lists and Keys",
            "useEffect and Side Effects",
            "Forms and Controlled Components",
            "Component Lifecycle",
            "Context API and Global State",
            "React Router and Navigation",
            "Custom Hooks",
            "API Integration with fetch/axios",
            "Error Boundaries",
            "Performance: React.memo, useMemo",
            "Mini Project: Build a Dashboard",
            "Testing with React Testing Library",
            "Practice and Review",
        ]
    },
    "sql": {
        "name": "SQL and Databases",
        "topics": [
            "Database Concepts and Relational Model",
            "CREATE TABLE and Data Types",
            "INSERT, UPDATE, DELETE",
            "SELECT Queries and WHERE Clause",
            "Sorting with ORDER BY",
            "Aggregate Functions: COUNT, SUM, AVG",
            "GROUP BY and HAVING",
            "JOIN Types: INNER, LEFT, RIGHT, FULL",
            "Subqueries and Nested Queries",
            "Views and Indexes",
            "Normalisation: 1NF, 2NF, 3NF",
            "Primary Keys and Foreign Keys",
            "Transactions and ACID Properties",
            "Stored Procedures and Functions",
            "Query Optimisation Basics",
            "Practice: Complex Query Challenges",
            "Review and Self-Assessment",
        ]
    },
    "data structures": {
        "name": "Data Structures and Algorithms",
        "topics": [
            "Big O Notation and Complexity Analysis",
            "Arrays and Dynamic Arrays",
            "Linked Lists: Singly and Doubly",
            "Stacks: Theory and Implementation",
            "Queues and Priority Queues",
            "Hash Tables and Hash Maps",
            "Binary Trees and Traversals",
            "Binary Search Trees (BST)",
            "Heaps and Heap Sort",
            "Graphs: Representation and BFS",
            "Graphs: DFS and Topological Sort",
            "Sorting: Bubble, Selection, Insertion",
            "Sorting: Merge Sort and Quick Sort",
            "Searching: Binary Search",
            "Recursion and Backtracking",
            "Dynamic Programming Introduction",
            "Dynamic Programming: Classic Problems",
            "Greedy Algorithms",
            "Practice: LeetCode-Style Problems",
            "Review and Exam Preparation",
        ]
    },
    "networking": {
        "name": "Computer Networking",
        "topics": [
            "OSI Model: 7 Layers Overview",
            "TCP/IP Protocol Suite",
            "Physical Layer and Data Transmission",
            "Data Link Layer and MAC Addresses",
            "Network Layer: IP Addressing",
            "Subnetting and CIDR Notation",
            "Transport Layer: TCP vs UDP",
            "Application Layer: HTTP, DNS, SMTP",
            "Routing Protocols: RIP, OSPF, BGP",
            "Switching and VLANs",
            "Wireless Networking: Wi-Fi Standards",
            "Network Security: Firewalls and VPNs",
            "DNS Deep Dive",
            "DHCP and NAT",
            "Socket Programming Basics",
            "Practice Questions and Review",
        ]
    },
    "software engineering": {
        "name": "Software Engineering",
        "topics": [
            "SDLC Models: Waterfall, Agile, Spiral",
            "Requirements Gathering and Analysis",
            "Use Case Diagrams and User Stories",
            "System Architecture and Design Patterns",
            "UML: Class and Sequence Diagrams",
            "Version Control with Git",
            "Testing: Unit, Integration, System",
            "Test-Driven Development (TDD)",
            "Continuous Integration/Deployment",
            "Code Quality and Refactoring",
            "Agile: Scrum Framework",
            "Agile: Kanban and Sprint Planning",
            "Project Management and Estimation",
            "Documentation and Technical Writing",
            "Ethics in Software Engineering",
            "Practice: Case Study Analysis",
            "Review and Exam Preparation",
        ]
    },
    "web development": {
        "name": "Web Development",
        "topics": [
            "How the Web Works: HTTP and Browsers",
            "HTML5 Semantic Structure",
            "CSS3 Layouts: Flexbox and Grid",
            "Responsive Design Principles",
            "JavaScript DOM Manipulation",
            "Frontend Frameworks Overview",
            "Backend Basics: Node.js/Express or Flask",
            "REST API Design",
            "Database Integration",
            "Authentication and Sessions",
            "Deployment: Hosting and Domains",
            "Performance Optimisation",
            "Security: XSS, CSRF, SQL Injection",
            "Accessibility (WCAG) Standards",
            "Full-Stack Mini Project",
            "Practice and Portfolio Building",
        ]
    },
    "artificial intelligence": {
        "name": "Artificial Intelligence",
        "topics": [
            "What is AI: History and Foundations",
            "Intelligent Agents and Environments",
            "Search Algorithms: BFS, DFS, A*",
            "Heuristic Search and Optimisation",
            "Constraint Satisfaction Problems",
            "Knowledge Representation",
            "Propositional and First-Order Logic",
            "Probabilistic Reasoning and Bayes",
            "Decision Trees and Random Forests",
            "Neural Networks: Perceptrons",
            "Deep Learning: CNNs and RNNs",
            "Natural Language Processing Basics",
            "Reinforcement Learning Introduction",
            "Ethics in AI and Bias",
            "AI Applications and Case Studies",
            "Practice Problems and Review",
        ]
    },
    "machine learning": {
        "name": "Machine Learning",
        "topics": [
            "ML Overview: Supervised vs Unsupervised",
            "Linear Regression",
            "Logistic Regression and Classification",
            "Decision Trees and Ensemble Methods",
            "Support Vector Machines",
            "K-Nearest Neighbours",
            "K-Means Clustering",
            "Dimensionality Reduction: PCA",
            "Neural Networks Fundamentals",
            "Training: Loss Functions and Gradient Descent",
            "Overfitting, Regularisation and Cross-Validation",
            "Feature Engineering and Selection",
            "Model Evaluation Metrics",
            "Scikit-learn Practical Session",
            "Deep Learning with TensorFlow/PyTorch Intro",
            "Mini Project: End-to-End ML Pipeline",
            "Review and Exam Preparation",
        ]
    },
    "cybersecurity": {
        "name": "Cybersecurity",
        "topics": [
            "CIA Triad: Confidentiality, Integrity, Availability",
            "Threat Landscape and Attack Vectors",
            "Cryptography: Symmetric Encryption",
            "Cryptography: Asymmetric and Hashing",
            "Network Security and Firewalls",
            "Authentication and Access Control",
            "Web Security: XSS, CSRF, SQL Injection",
            "Malware Types and Analysis",
            "Social Engineering and Phishing",
            "Penetration Testing Methodology",
            "Incident Response and Forensics",
            "Security Policies and Compliance",
            "Wireless Security",
            "Cloud Security Basics",
            "Ethical Hacking and Legal Framework",
            "Practice: CTF-Style Challenges",
        ]
    },
    "operating systems": {
        "name": "Operating Systems",
        "topics": [
            "OS Overview: Roles and Types",
            "Process Management and Scheduling",
            "CPU Scheduling Algorithms",
            "Threads and Concurrency",
            "Process Synchronisation and Deadlocks",
            "Memory Management: Paging",
            "Virtual Memory and Page Replacement",
            "File Systems and Directory Structure",
            "I/O Management and Device Drivers",
            "Disk Scheduling Algorithms",
            "Security and Protection",
            "Linux Command Line Essentials",
            "Shell Scripting Basics",
            "Practice Questions and Past Papers",
            "Review and Exam Preparation",
        ]
    },

    # ===== MATHEMATICS =====
    "calculus": {
        "name": "Calculus",
        "topics": [
            "Limits and Continuity",
            "Derivatives: Definition and Rules",
            "Power Rule, Product Rule, Quotient Rule",
            "Chain Rule and Implicit Differentiation",
            "Applications: Maxima and Minima",
            "Related Rates Problems",
            "Curve Sketching and Analysis",
            "Integration: Antiderivatives",
            "Definite Integrals and Area Under Curves",
            "Integration Techniques: Substitution",
            "Integration by Parts",
            "Applications of Integration: Volume",
            "Differential Equations Introduction",
            "Sequences and Series",
            "Taylor and Maclaurin Series",
            "Practice: Mixed Problem Set",
            "Past Paper Questions and Review",
        ]
    },
    "algebra": {
        "name": "Algebra",
        "topics": [
            "Linear Equations and Inequalities",
            "Quadratic Equations and Factoring",
            "Simultaneous Equations",
            "Polynomials and Factorisation",
            "Indices and Surds",
            "Functions: Domain, Range, Inverse",
            "Logarithms and Exponentials",
            "Sequences: Arithmetic and Geometric",
            "Partial Fractions",
            "Binomial Theorem",
            "Matrices: Operations and Determinants",
            "Matrix Inverses and Systems of Equations",
            "Vectors and Vector Spaces",
            "Complex Numbers",
            "Practice Problems and Past Papers",
            "Review and Exam Preparation",
        ]
    },
    "statistics": {
        "name": "Statistics",
        "topics": [
            "Data Types and Collection Methods",
            "Measures of Central Tendency",
            "Measures of Spread: Range, IQR, Std Dev",
            "Data Visualisation: Histograms, Box Plots",
            "Probability: Basic Rules and Trees",
            "Conditional Probability and Bayes Theorem",
            "Discrete Distributions: Binomial, Poisson",
            "Continuous Distributions: Normal",
            "Sampling and Sampling Distributions",
            "Confidence Intervals",
            "Hypothesis Testing: z-test and t-test",
            "Chi-Squared Tests",
            "Correlation and Regression",
            "ANOVA Introduction",
            "Practice: Statistical Analysis Problems",
            "Past Papers and Review",
        ]
    },
    "discrete maths": {
        "name": "Discrete Mathematics",
        "topics": [
            "Propositional Logic and Truth Tables",
            "Predicate Logic and Quantifiers",
            "Proof Techniques: Direct, Contradiction",
            "Mathematical Induction",
            "Set Theory and Operations",
            "Relations and Functions",
            "Counting: Permutations and Combinations",
            "Pigeonhole Principle",
            "Graph Theory: Definitions and Properties",
            "Graph Traversals and Connectivity",
            "Trees and Spanning Trees",
            "Planar Graphs and Colouring",
            "Boolean Algebra and Logic Gates",
            "Finite State Machines",
            "Recurrence Relations",
            "Practice Problems and Review",
        ]
    },
    "linear algebra": {
        "name": "Linear Algebra",
        "topics": [
            "Vectors and Vector Operations",
            "Dot Product and Cross Product",
            "Matrix Operations: Addition, Multiplication",
            "Matrix Transpose and Symmetric Matrices",
            "Determinants and Properties",
            "Inverse Matrices",
            "Systems of Linear Equations",
            "Gaussian Elimination",
            "Vector Spaces and Subspaces",
            "Linear Independence and Basis",
            "Eigenvalues and Eigenvectors",
            "Diagonalisation",
            "Orthogonality and Gram-Schmidt",
            "Applications: Transformations",
            "Practice Problems and Review",
        ]
    },

    # ===== SCIENCES =====
    "physics": {
        "name": "Physics",
        "topics": [
            "Units, Measurements and Errors",
            "Kinematics: Speed, Velocity, Acceleration",
            "Newton's Laws of Motion",
            "Forces: Friction, Tension, Normal",
            "Work, Energy and Power",
            "Momentum and Collisions",
            "Circular Motion and Gravitation",
            "Simple Harmonic Motion",
            "Waves: Properties and Behaviour",
            "Sound and Light Waves",
            "Electricity: Current, Voltage, Resistance",
            "DC Circuits and Kirchhoff's Laws",
            "Electromagnetism and Induction",
            "Nuclear Physics and Radioactivity",
            "Thermodynamics Basics",
            "Practice Problems and Past Papers",
            "Review and Exam Preparation",
        ]
    },
    "chemistry": {
        "name": "Chemistry",
        "topics": [
            "Atomic Structure and Electron Config",
            "Periodic Table and Trends",
            "Chemical Bonding: Ionic and Covalent",
            "Moles, Mass and Concentration",
            "Balancing Chemical Equations",
            "Energetics: Enthalpy Changes",
            "Rates of Reaction and Catalysts",
            "Chemical Equilibrium",
            "Acids, Bases and pH",
            "Redox Reactions and Electrochemistry",
            "Organic Chemistry: Alkanes and Alkenes",
            "Organic: Alcohols, Aldehydes, Ketones",
            "Organic: Carboxylic Acids and Esters",
            "Organic Reaction Mechanisms",
            "Analytical Techniques: IR, Mass Spec",
            "Practice Questions and Past Papers",
            "Review and Exam Preparation",
        ]
    },
    "biology": {
        "name": "Biology",
        "topics": [
            "Cell Structure: Prokaryotic vs Eukaryotic",
            "Cell Membrane and Transport",
            "Enzymes and Metabolic Reactions",
            "DNA Structure and Replication",
            "Protein Synthesis: Transcription/Translation",
            "Cell Division: Mitosis and Meiosis",
            "Genetics: Mendel's Laws",
            "Gene Expression and Mutations",
            "Evolution and Natural Selection",
            "Classification and Biodiversity",
            "Photosynthesis",
            "Cellular Respiration",
            "Human Circulatory System",
            "Nervous System and Homeostasis",
            "Immune System and Disease",
            "Ecology and Ecosystems",
            "Practice Questions and Past Papers",
            "Review and Exam Preparation",
        ]
    },

    # ===== BUSINESS & ECONOMICS =====
    "economics": {
        "name": "Economics",
        "topics": [
            "Supply and Demand Fundamentals",
            "Elasticity: Price, Income, Cross",
            "Market Structures: Perfect Competition",
            "Monopoly and Oligopoly",
            "Market Failure and Externalities",
            "Government Intervention: Tax, Subsidies",
            "GDP, Growth and the Business Cycle",
            "Inflation and Unemployment",
            "Monetary Policy and Central Banks",
            "Fiscal Policy and Government Spending",
            "International Trade and Globalisation",
            "Exchange Rates and Balance of Payments",
            "Development Economics",
            "Practice: Essay Planning and Data Response",
            "Past Papers and Review",
        ]
    },
    "accounting": {
        "name": "Accounting",
        "topics": [
            "Double Entry Bookkeeping",
            "Trial Balance and Adjustments",
            "Income Statement (Profit and Loss)",
            "Balance Sheet (Statement of Financial Position)",
            "Cash Flow Statement",
            "Depreciation Methods",
            "Inventory Valuation",
            "Bank Reconciliation",
            "Accruals and Prepayments",
            "Ratio Analysis: Profitability",
            "Ratio Analysis: Liquidity and Efficiency",
            "Budgeting and Variance Analysis",
            "Cost Accounting Basics",
            "Practice Questions and Scenarios",
            "Review and Exam Preparation",
        ]
    },
    "business studies": {
        "name": "Business Studies",
        "topics": [
            "Business Objectives and Stakeholders",
            "Market Research and Analysis",
            "Marketing Mix: 4Ps",
            "Human Resource Management",
            "Motivation Theories: Maslow, Herzberg",
            "Organisational Structure",
            "Leadership and Management Styles",
            "Finance: Sources and Cash Flow",
            "Break-Even Analysis",
            "Operations Management",
            "Quality Management and Lean Production",
            "Business Strategy and SWOT Analysis",
            "Globalisation and International Business",
            "Business Ethics and CSR",
            "Practice: Case Study Analysis",
            "Review and Exam Preparation",
        ]
    },

    # ===== HUMANITIES =====
    "psychology": {
        "name": "Psychology",
        "topics": [
            "Research Methods and Ethics",
            "Biological Approach: Brain and Neurons",
            "Cognitive Approach: Memory Models",
            "Behaviourist Approach: Classical/Operant",
            "Social Learning Theory: Bandura",
            "Psychodynamic Approach: Freud",
            "Humanistic Approach: Maslow, Rogers",
            "Attachment Theory: Bowlby and Ainsworth",
            "Social Influence: Conformity",
            "Social Influence: Obedience (Milgram)",
            "Memory: Multi-Store and Working Memory",
            "Psychopathology: Depression and OCD",
            "Biopsychology: Nervous System",
            "Statistical Tests and Data Analysis",
            "Essay Writing Skills for Psychology",
            "Past Papers and Review",
        ]
    },
    "sociology": {
        "name": "Sociology",
        "topics": [
            "Sociological Perspectives: Functionalism",
            "Marxism and Social Class",
            "Feminism and Gender Inequality",
            "Interactionism and Labelling",
            "Research Methods: Surveys and Interviews",
            "Education: Achievement and Policy",
            "Family: Structures and Diversity",
            "Crime and Deviance",
            "Media and Identity",
            "Stratification and Social Mobility",
            "Globalisation and Culture",
            "Essay Planning and Structure",
            "Practice Questions and Review",
        ]
    },
    "history": {
        "name": "History",
        "topics": [
            "Source Analysis Techniques",
            "Essay Structure and Argumentation",
            "Key Period: Context and Causes",
            "Key Period: Major Events and Turning Points",
            "Key Period: Key Figures and Leadership",
            "Key Period: Social and Economic Impact",
            "Key Period: Consequences and Legacy",
            "Historiography: Different Interpretations",
            "Timeline and Chronology Review",
            "Primary Source Evaluation Practice",
            "Essay Practice: Structured Argument",
            "Past Paper Questions",
            "Review and Exam Preparation",
        ]
    },
    "english literature": {
        "name": "English Literature",
        "topics": [
            "Close Reading and Annotation Skills",
            "Literary Techniques: Imagery and Metaphor",
            "Narrative Voice and Perspective",
            "Character Analysis Methods",
            "Theme Identification and Tracking",
            "Context: Social, Historical, Cultural",
            "Poetry Analysis Framework",
            "Prose Analysis: Structure and Style",
            "Drama Analysis: Stage and Dialogue",
            "Comparative Essay Technique",
            "Critical Theory Introduction",
            "Essay Planning and Thesis Development",
            "Quotation Selection and Integration",
            "Practice Essay Writing",
            "Past Papers and Review",
        ]
    },
    "philosophy": {
        "name": "Philosophy",
        "topics": [
            "What is Philosophy: Branches Overview",
            "Epistemology: Knowledge and Belief",
            "Rationalism vs Empiricism",
            "Ethics: Utilitarianism",
            "Ethics: Deontology and Kant",
            "Ethics: Virtue Ethics",
            "Philosophy of Mind: Dualism vs Physicalism",
            "Free Will and Determinism",
            "Political Philosophy: Social Contract",
            "Logic and Argumentation",
            "Existentialism: Sartre and Camus",
            "Philosophy of Religion",
            "Critical Analysis and Essay Writing",
            "Practice and Review",
        ]
    },

    # ===== LANGUAGES =====
    "spanish": {
        "name": "Spanish Language",
        "topics": [
            "Greetings and Basic Phrases",
            "Numbers, Dates and Time",
            "Present Tense: Regular Verbs",
            "Present Tense: Irregular Verbs",
            "Articles, Nouns and Adjectives",
            "Family, Friends and Descriptions",
            "Food, Drink and Restaurants",
            "Hobbies and Free Time",
            "Past Tense: Preterite",
            "Past Tense: Imperfect",
            "Future Tense",
            "Subjunctive Mood Introduction",
            "Travel and Directions Vocabulary",
            "Work and Education Vocabulary",
            "Reading Comprehension Practice",
            "Listening Practice and Review",
        ]
    },
    "french": {
        "name": "French Language",
        "topics": [
            "Greetings and Introductions",
            "Numbers, Dates and Time",
            "Present Tense: Regular -er, -ir, -re",
            "Present Tense: Irregular Verbs",
            "Articles and Gender Agreement",
            "Family and Physical Descriptions",
            "Food and Ordering at Restaurants",
            "Hobbies and Leisure",
            "Past Tense: Passe Compose",
            "Past Tense: Imparfait",
            "Future Tense and Conditional",
            "Pronouns: Direct and Indirect Object",
            "Travel and Accommodation Vocabulary",
            "School and Work Vocabulary",
            "Reading and Listening Practice",
            "Review and Exam Preparation",
        ]
    },

    # ===== ENGINEERING =====
    "electrical engineering": {
        "name": "Electrical Engineering",
        "topics": [
            "DC Circuit Analysis: Ohm's Law",
            "Series and Parallel Circuits",
            "Kirchhoff's Current and Voltage Laws",
            "Thevenin and Norton Theorems",
            "AC Circuit Analysis: Phasors",
            "Impedance and Reactance",
            "Capacitors and Inductors",
            "Resonance and Filters",
            "Transformers and Power Transfer",
            "Semiconductors: Diodes",
            "Transistors: BJT and MOSFET",
            "Operational Amplifiers",
            "Digital Logic: Gates and Boolean Algebra",
            "Practice Problems and Review",
        ]
    },
    "mechanical engineering": {
        "name": "Mechanical Engineering",
        "topics": [
            "Statics: Forces and Equilibrium",
            "Free Body Diagrams",
            "Moments and Torque",
            "Stress, Strain and Elasticity",
            "Beam Bending and Shear Force Diagrams",
            "Dynamics: Newton's Laws Applied",
            "Work, Energy and Power",
            "Thermodynamics: Laws and Cycles",
            "Heat Transfer: Conduction, Convection",
            "Fluid Mechanics: Pressure and Flow",
            "Bernoulli's Equation and Applications",
            "Material Properties and Selection",
            "Practice Problems and Review",
        ]
    },

    # ===== MEDICAL / HEALTH =====
    "anatomy": {
        "name": "Anatomy and Physiology",
        "topics": [
            "Body Organisation and Terminology",
            "Skeletal System: Bones and Joints",
            "Muscular System: Types and Function",
            "Cardiovascular System: Heart",
            "Cardiovascular System: Blood Vessels",
            "Respiratory System",
            "Digestive System",
            "Nervous System: Brain and Spinal Cord",
            "Endocrine System: Hormones",
            "Urinary System: Kidneys",
            "Immune and Lymphatic System",
            "Reproductive System",
            "Integumentary System: Skin",
            "Practice: Labelling and Identification",
            "Review and Exam Preparation",
        ]
    },
    "nursing": {
        "name": "Nursing Studies",
        "topics": [
            "Patient Assessment and Vital Signs",
            "Infection Control and Hygiene",
            "Medication Administration",
            "Fluid Balance and Nutrition",
            "Wound Care and Healing",
            "Pain Management",
            "Communication Skills in Healthcare",
            "Documentation and Record Keeping",
            "Patient Safety and Risk Assessment",
            "Ethics and Professional Standards",
            "Mental Health Nursing Basics",
            "End of Life Care and Palliative",
            "Evidence-Based Practice",
            "Clinical Skills Practice",
            "Review and Exam Preparation",
        ]
    },

    # ===== ACADEMIC SKILLS =====
    "essay writing": {
        "name": "Academic Essay Writing",
        "topics": [
            "Understanding Essay Questions",
            "Research Strategies and Source Finding",
            "Evaluating Source Credibility",
            "Thesis Statement Development",
            "Essay Structure: Introduction Techniques",
            "Body Paragraphs: PEEL/PEAR Method",
            "Linking Arguments and Transitions",
            "Counter-Arguments and Rebuttal",
            "Conclusion Writing Techniques",
            "Referencing: Harvard/APA Style",
            "Avoiding Plagiarism",
            "Editing and Proofreading",
            "Practice: Timed Essay Writing",
            "Review and Self-Assessment",
        ]
    },
    "dissertation": {
        "name": "Dissertation Writing",
        "topics": [
            "Choosing and Refining Your Topic",
            "Literature Search Strategy",
            "Writing the Literature Review",
            "Research Methodology Selection",
            "Ethics Application and Approval",
            "Data Collection Planning",
            "Data Analysis: Qualitative Methods",
            "Data Analysis: Quantitative Methods",
            "Writing the Methodology Chapter",
            "Writing the Results Chapter",
            "Discussion and Critical Analysis",
            "Conclusion and Recommendations",
            "Abstract and Executive Summary",
            "Formatting, References and Appendices",
            "Proofreading and Final Submission Prep",
        ]
    },
    "research methods": {
        "name": "Research Methods",
        "topics": [
            "Quantitative vs Qualitative Research",
            "Research Design: Experimental",
            "Research Design: Surveys and Questionnaires",
            "Research Design: Case Studies",
            "Sampling Methods and Bias",
            "Data Collection Techniques",
            "Validity and Reliability",
            "Ethics in Research",
            "Descriptive Statistics",
            "Inferential Statistics: t-test, Chi-Square",
            "Thematic Analysis",
            "Content Analysis",
            "Mixed Methods Approach",
            "Writing a Research Proposal",
            "Practice and Review",
        ]
    },
    "exam prep": {
        "name": "Exam Preparation",
        "topics": [
            "Review Lecture Notes and Highlights",
            "Create Mind Maps and Summaries",
            "Active Recall: Flashcard Session",
            "Practice Past Paper: Timed Conditions",
            "Mark and Review Past Paper Answers",
            "Identify Weak Topics and Target Review",
            "Spaced Repetition Review Session",
            "Practice Past Paper: Second Attempt",
            "Group Discussion or Peer Teaching",
            "Formula/Key Concept Sheet Creation",
            "Final Review: High-Priority Topics",
            "Exam Technique: Time Management",
            "Relaxation and Confidence Building",
        ]
    },
}

KEYWORD_ALIASES = {
    "python programming": "python", "py": "python", "python3": "python",
    "java programming": "java", "javascript programming": "javascript", "js": "javascript", "node": "javascript", "nodejs": "javascript",
    "c plus plus": "c++", "cpp": "c++",
    "c sharp": "c#", "csharp": "c#",
    "html": "html css", "css": "html css", "html/css": "html css", "web design": "html css",
    "react js": "react", "reactjs": "react", "react native": "react",
    "database": "sql", "databases": "sql", "mysql": "sql", "postgresql": "sql", "sqlite": "sql",
    "dsa": "data structures", "algorithms": "data structures", "data structures and algorithms": "data structures", "leetcode": "data structures",
    "networks": "networking", "computer networks": "networking", "network": "networking",
    "se": "software engineering", "software development": "software engineering",
    "web dev": "web development", "full stack": "web development", "fullstack": "web development", "frontend": "web development", "backend": "web development",
    "ai": "artificial intelligence", "artificial intelligence": "artificial intelligence",
    "ml": "machine learning",
    "cyber": "cybersecurity", "security": "cybersecurity", "infosec": "cybersecurity", "ethical hacking": "cybersecurity",
    "os": "operating systems",
    "calc": "calculus", "calculus revision": "calculus",
    "maths": "algebra", "math": "algebra", "mathematics": "algebra", "algebra revision": "algebra",
    "stats": "statistics", "probability": "statistics",
    "discrete": "discrete maths", "discrete mathematics": "discrete maths",
    "lin alg": "linear algebra",
    "bio": "biology", "biology revision": "biology",
    "chem": "chemistry", "chemistry revision": "chemistry",
    "phys": "physics", "physics revision": "physics",
    "econ": "economics", "microeconomics": "economics", "macroeconomics": "economics",
    "business": "business studies",
    "psych": "psychology",
    "soc": "sociology",
    "eng lit": "english literature", "literature": "english literature", "english": "english literature",
    "phil": "philosophy",
    "espanol": "spanish",
    "francais": "french",
    "ee": "electrical engineering", "electronics": "electrical engineering", "circuits": "electrical engineering",
    "me": "mechanical engineering", "mechanics": "mechanical engineering", "statics": "mechanical engineering",
    "a&p": "anatomy", "anatomy and physiology": "anatomy", "physiology": "anatomy",
    "essay": "essay writing", "essays": "essay writing", "academic writing": "essay writing",
    "diss": "dissertation", "thesis": "dissertation", "final year project": "dissertation",
    "research": "research methods",
    "exam": "exam prep", "revision": "exam prep", "exam revision": "exam prep", "past papers": "exam prep", "exam preparation": "exam prep",
}


def match_subject(user_input):
    query = user_input.lower().strip()

    if query in CURRICULUM_DB:
        return CURRICULUM_DB[query]

    if query in KEYWORD_ALIASES:
        key = KEYWORD_ALIASES[query]
        return CURRICULUM_DB.get(key)

    for alias, key in KEYWORD_ALIASES.items():
        if alias in query or query in alias:
            return CURRICULUM_DB.get(key)

    for key, subject in CURRICULUM_DB.items():
        if key in query or query in key:
            return subject
        if query in subject['name'].lower():
            return subject

    return None


def generate_curriculum(user_input, total_sessions):
    subject = match_subject(user_input)

    if subject:
        topics = subject['topics']
        plan = []
        for i in range(total_sessions):
            topic_index = i % len(topics)
            cycle = i // len(topics)
            if cycle == 0:
                plan.append(f"{subject['name']}: {topics[topic_index]}")
            else:
                plan.append(f"{subject['name']} Review: {topics[topic_index]}")
        return plan, subject['name']
    else:
        generic_plan = [
            f"{user_input}: Review Notes and Key Concepts",
            f"{user_input}: Practice Questions",
            f"{user_input}: Past Paper Attempt",
            f"{user_input}: Weak Areas Deep Dive",
            f"{user_input}: Summary and Mind Maps",
            f"{user_input}: Timed Practice Session",
            f"{user_input}: Flashcards and Active Recall",
            f"{user_input}: Self-Assessment Quiz",
            f"{user_input}: Group Study or Peer Teaching",
            f"{user_input}: Final Review and Consolidation",
        ]
        plan = []
        for i in range(total_sessions):
            plan.append(generic_plan[i % len(generic_plan)])
        return plan, user_input.title()