from ics import Calendar, Event
from datetime import datetime, timedelta
import io

def generate_ics_file(tasks):
    """
    Takes a list of scheduled tasks and converts them into a
    standard .ics calendar file (compatible with Outlook, Google, Apple).
    """
    c = Calendar()

    # Filter for tasks that actually have a start time
    scheduled_tasks = [t for t in tasks if t.get('start_time')]

    for t in scheduled_tasks:
        e = Event()
        e.name = f"📝 {t['name']}"  # Add emoji to title

        # Convert strings back to datetime if needed
        start_dt = t['start_time']
        if isinstance(start_dt, str):
            start_dt = datetime.fromisoformat(start_dt)

        end_dt = t['end_time']
        if isinstance(end_dt, str):
            end_dt = datetime.fromisoformat(end_dt)

        e.begin = start_dt
        e.end = end_dt

        # Add details to the description
        notes = t.get('notes', 'No notes added.')
        e.description = f"Priority: {t['priority'].upper()}\nNotes: {notes}\n\nGenerated by ScheduleSmart 🚀"

        c.events.add(e)

    # Return the file as a downloadable string
    return c.serialize()
